"""Initial migration

Revision ID: 220ce2c11cb2
Revises: 
Create Date: 2024-09-05 12:07:37.845899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220ce2c11cb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_symbol', sa.String(length=20), nullable=True))
        batch_op.drop_column('selected_stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_stock', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('selected_symbol')

    # ### end Alembic commands ###
